# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1132, 938)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QPushButton\n"
"{\n"
"    color: white;\n"
"    background-color: red;\n"
"    padding: 10px;\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: coral;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("QTextBrowser, QTextEdit\n"
"{\n"
"    border-top: none;\n"
"    border-left: 1px solid lightgrey;\n"
"    border-right: 1px solid lightgrey;\n"
"    border-bottom: 2px solid lightgrey;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.startPage = QtWidgets.QWidget()
        self.startPage.setObjectName("startPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.startPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.startButton = QtWidgets.QPushButton(self.startPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startButton.setStyleSheet("QPushButton\n"
"{\n"
"    padding: 5px;\n"
"}")
        self.startButton.setObjectName("startButton")
        self.verticalLayout_3.addWidget(self.startButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.stackedWidget.addWidget(self.startPage)
        self.typePage = QtWidgets.QWidget()
        self.typePage.setObjectName("typePage")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.typePage)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(30, 10, 30, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lHeader = QtWidgets.QLabel(self.typePage)
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.lHeader.setFont(font)
        self.lHeader.setTextFormat(QtCore.Qt.AutoText)
        self.lHeader.setObjectName("lHeader")
        self.verticalLayout.addWidget(self.lHeader, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.expectedText = ExpectedTextBrowser(self.typePage)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        self.expectedText.setFont(font)
        self.expectedText.setStyleSheet("")
        self.expectedText.setReadOnly(True)
        self.expectedText.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.expectedText.setObjectName("expectedText")
        self.verticalLayout.addWidget(self.expectedText)
        self.textEdit = TypingTextEdit(self.typePage)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem1)
        self.typingNextButton = QtWidgets.QPushButton(self.typePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typingNextButton.sizePolicy().hasHeightForWidth())
        self.typingNextButton.setSizePolicy(sizePolicy)
        self.typingNextButton.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.typingNextButton.setFont(font)
        self.typingNextButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.typingNextButton.setAutoFillBackground(False)
        self.typingNextButton.setStyleSheet("")
        self.typingNextButton.setAutoDefault(False)
        self.typingNextButton.setDefault(True)
        self.typingNextButton.setFlat(False)
        self.typingNextButton.setObjectName("typingNextButton")
        self.verticalLayout.addWidget(self.typingNextButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.stackedWidget.addWidget(self.typePage)
        self.errorCheckPage = QtWidgets.QWidget()
        self.errorCheckPage.setObjectName("errorCheckPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.errorCheckPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.errorCheckArea = ErrorCheckingArea(self.errorCheckPage)
        self.errorCheckArea.setWidgetResizable(True)
        self.errorCheckArea.setObjectName("errorCheckArea")
        self.contents = QtWidgets.QWidget()
        self.contents.setGeometry(QtCore.QRect(0, 0, 1094, 879))
        self.contents.setObjectName("contents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.contents)
        self.verticalLayout_6.setContentsMargins(20, 0, 20, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.errHeader = QtWidgets.QLabel(self.contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errHeader.sizePolicy().hasHeightForWidth())
        self.errHeader.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.errHeader.setFont(font)
        self.errHeader.setStyleSheet("QLabel {\n"
"    padding: 10px;\n"
"}")
        self.errHeader.setObjectName("errHeader")
        self.verticalLayout_6.addWidget(self.errHeader, 0, QtCore.Qt.AlignHCenter)
        self.txtTooltip = QtWidgets.QLabel(self.contents)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.txtTooltip.setFont(font)
        self.txtTooltip.setStyleSheet("QLabel {\n"
"    margin-left: 10px;\n"
"}")
        self.txtTooltip.setObjectName("txtTooltip")
        self.verticalLayout_6.addWidget(self.txtTooltip)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem3)
        self.imgErrorLabel = QtWidgets.QLabel(self.contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgErrorLabel.sizePolicy().hasHeightForWidth())
        self.imgErrorLabel.setSizePolicy(sizePolicy)
        self.imgErrorLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.imgErrorLabel.setMaximumSize(QtCore.QSize(999999, 999999))
        self.imgErrorLabel.setBaseSize(QtCore.QSize(0, 0))
        self.imgErrorLabel.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.imgErrorLabel.setText("")
        self.imgErrorLabel.setScaledContents(True)
        self.imgErrorLabel.setObjectName("imgErrorLabel")
        self.verticalLayout_6.addWidget(self.imgErrorLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem4)
        self.lErrorCheckQuestion = QtWidgets.QTextBrowser(self.contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lErrorCheckQuestion.sizePolicy().hasHeightForWidth())
        self.lErrorCheckQuestion.setSizePolicy(sizePolicy)
        self.lErrorCheckQuestion.setMinimumSize(QtCore.QSize(0, 0))
        self.lErrorCheckQuestion.setSizeIncrement(QtCore.QSize(0, 0))
        self.lErrorCheckQuestion.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.lErrorCheckQuestion.setFont(font)
        self.lErrorCheckQuestion.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lErrorCheckQuestion.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lErrorCheckQuestion.setStyleSheet("")
        self.lErrorCheckQuestion.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.lErrorCheckQuestion.setAutoFormatting(QtWidgets.QTextEdit.AutoBulletList)
        self.lErrorCheckQuestion.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.lErrorCheckQuestion.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lErrorCheckQuestion.setObjectName("lErrorCheckQuestion")
        self.verticalLayout_6.addWidget(self.lErrorCheckQuestion, 0, QtCore.Qt.AlignVCenter)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem5)
        self.cmbErrorCheck = QtWidgets.QComboBox(self.contents)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.cmbErrorCheck.setFont(font)
        self.cmbErrorCheck.setObjectName("cmbErrorCheck")
        self.verticalLayout_6.addWidget(self.cmbErrorCheck)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.errorCheckNextButton = QtWidgets.QPushButton(self.contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errorCheckNextButton.sizePolicy().hasHeightForWidth())
        self.errorCheckNextButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.errorCheckNextButton.setFont(font)
        self.errorCheckNextButton.setObjectName("errorCheckNextButton")
        self.verticalLayout_6.addWidget(self.errorCheckNextButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem7)
        self.errorCheckArea.setWidget(self.contents)
        self.verticalLayout_5.addWidget(self.errorCheckArea)
        self.stackedWidget.addWidget(self.errorCheckPage)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1132, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.lHeader.setText(_translate("MainWindow", "Typing Test"))
        self.expectedText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.typingNextButton.setText(_translate("MainWindow", "Submit"))
        self.errHeader.setText(_translate("MainWindow", "Error Checking"))
        self.txtTooltip.setText(_translate("MainWindow", "See image, read the question, and choose the right answer below:"))
        self.lErrorCheckQuestion.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">test</p></body></html>"))
        self.errorCheckNextButton.setText(_translate("MainWindow", "Submit"))
from src.ErrorCheckingArea import ErrorCheckingArea
from src.ExpectedTextBrowser import ExpectedTextBrowser
from src.TypingTextEdit import TypingTextEdit
